POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiYzJAZ21haWwuY29tIiwiZXhwIjoxNzYyMDYyNDcyLCJ1c2VySWQiOjJ9.UjutMTSMAlsSbv3ZfpHpC6IEoqLgbTIUT3WR23ClEls
